### ISSUE TITLE
Unexpected fault address fatal error

### ISSUE THREAD

**Issue by julienfouilhe** [bitly/go-nsq#118]
Hi,

I didn't update go-nsq for a long time I must say, maybe 3 weeks, but I just did install for program on a ubuntu server (thus every dependency has been checked out), and I get this weird error that I never saw before. As you can see, the error isn't really explicit.

I first thought it was coming from my code, and it may be still, but as I can't find why it would do that and as go-nsq appears a lot in there, I prefer to post it here hoping that anyone would have an idea where it comes from.

**It seems** to appear only when there's concurrent nsq access (producing several messages and receiving several messages at same time)

```bash
unexpected fault address 0x7f9000000011
fatal error: fault
[signal 0xb code=0x1 addr=0x7f9000000011]

goroutine 2087 [running]:

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

goroutine 1 [select]:
main.main
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:178

goroutine 8 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 9 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 140 [select]:
craft.getDataFromDatas
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:102
github.com_testar_test_mount_of_doom_craft.GetTestData
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:141
main.craftTestID
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft_test.go:232
main.handleCraftTestMessage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:95
main.$nested0
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:122
created by main.handlePackage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:121

goroutine 13 [IO wait]:
github.com_bitly_go_nsq.Read.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:238
github.com_bitly_go_nsq.ReadResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:54
github.com_bitly_go_nsq.ReadUnpackedResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:91
github.com_bitly_go_nsq.readLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:475
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:176

goroutine 14 [select]:
github.com_bitly_go_nsq.writeLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:541
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:177

goroutine 15 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 16 [chan receive]:
qlib.handleInternal
	/home/ubuntu/go/src/github.com/testar-test/go-qlib/client.go:230
created by github.com_testar_test_go_qlib.run.pN38_github.com_testar_test_go_qlib.Client
	/home/ubuntu/go/src/github.com/testar-test/go-qlib/client.go:224

goroutine 17 [IO wait]:
github.com_bitly_go_nsq.Read.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:238
github.com_bitly_go_nsq.ReadResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:54
github.com_bitly_go_nsq.ReadUnpackedResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:91
github.com_bitly_go_nsq.readLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:475
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:176

goroutine 18 [select]:
github.com_bitly_go_nsq.writeLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:541
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:177

goroutine 19 [select]:
github.com_bitly_go_nsq.router.pN32_github.com_bitly_go_nsq.Producer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/producer.go:261
created by github.com_bitly_go_nsq.connect.pN32_github.com_bitly_go_nsq.Producer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/producer.go:241

goroutine 20 [IO wait]:
github.com_gocql_gocql.recv.pN27_github.com_gocql_gocql.Conn
	/home/ubuntu/go/src/github.com/gocql/gocql/conn.go:262
github.com_gocql_gocql.serve.pN27_github.com_gocql_gocql.Conn
	/home/ubuntu/go/src/github.com/gocql/gocql/conn.go:240
created by github.com_gocql_gocql.Connect
	/home/ubuntu/go/src/github.com/gocql/gocql/conn.go:174

goroutine 22 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 23 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 28 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 29 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 30 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 34 [IO wait]:
github.com_bitly_go_nsq.Read.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:238
github.com_bitly_go_nsq.ReadResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:54
github.com_bitly_go_nsq.ReadUnpackedResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:91
github.com_bitly_go_nsq.readLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:475
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:176

goroutine 35 [select]:
github.com_bitly_go_nsq.writeLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:541
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:177

goroutine 36 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 37 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 38 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 42 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 43 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 44 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 48 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 49 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 50 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 54 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 132 [select]:
craft.getDataFromDatas
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:102
github.com_testar_test_mount_of_doom_craft.GetTestData
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:141
main.craftTestID
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft_test.go:232
main.handleCraftTestMessage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:95
main.$nested0
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:122
created by main.handlePackage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:121

goroutine 55 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 56 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 60 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 61 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 62 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 66 [IO wait]:
github.com_bitly_go_nsq.Read.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:238
github.com_bitly_go_nsq.ReadResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:54
github.com_bitly_go_nsq.ReadUnpackedResponse
	/home/ubuntu/go/src/github.com/bitly/go-nsq/protocol.go:91
github.com_bitly_go_nsq.readLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:475
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:176

goroutine 67 [select]:
github.com_bitly_go_nsq.writeLoop.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:541
created by github.com_bitly_go_nsq.Connect.pN28_github.com_bitly_go_nsq.Conn
	/home/ubuntu/go/src/github.com/bitly/go-nsq/conn.go:177

goroutine 68 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 69 [select]:
github.com_bitly_go_nsq.rdyLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:861
created by github.com_bitly_go_nsq.NewConsumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:178

goroutine 70 [chan receive]:
github.com_bitly_go_nsq.handlerLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1056
created by github.com_bitly_go_nsq.AddConcurrentHandlers.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:1048

goroutine 74 [select]:
github.com_bitly_go_nsq.lookupdLoop.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:377
created by github.com_bitly_go_nsq.ConnectToNSQLookupd.pN32_github.com_bitly_go_nsq.Consumer
	/home/ubuntu/go/src/github.com/bitly/go-nsq/consumer.go:324

goroutine 75 [select]:
github.com_testar_test_mount_of_doom_craft.HandleNewMarkers
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/marker.go:145
created by main.main
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:175

goroutine 76 [IO wait]:
github.com_gocql_gocql.recv.pN27_github.com_gocql_gocql.Conn
	/home/ubuntu/go/src/github.com/gocql/gocql/conn.go:262
github.com_gocql_gocql.serve.pN27_github.com_gocql_gocql.Conn
	/home/ubuntu/go/src/github.com/gocql/gocql/conn.go:240
created by github.com_gocql_gocql.Connect
	/home/ubuntu/go/src/github.com/gocql/gocql/conn.go:174

goroutine 151 [select]:
craft.getDataFromDatas
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:102
github.com_testar_test_mount_of_doom_craft.GetTestData
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:141
main.craftTestID
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft_test.go:232
main.handleCraftTestMessage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:95
main.$nested0
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:122
created by main.handlePackage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:121

goroutine 184 [select]:
craft.getDataFromDatas
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:102
github.com_testar_test_mount_of_doom_craft.GetTestData
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:141
main.craftTestID
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft_test.go:232
main.handleCraftTestMessage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:95
main.$nested0
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:122
created by main.handlePackage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:121

goroutine 2033 [select]:
github.com_AdRoll_goamz_s3.doHttpRequest.pN29_github.com_AdRoll_goamz_s3.S3
	/home/ubuntu/go/src/github.com/AdRoll/goamz/s3/s3.go:1144
github.com_AdRoll_goamz_s3.run.pN29_github.com_AdRoll_goamz_s3.S3
	/home/ubuntu/go/src/github.com/AdRoll/goamz/s3/s3.go:1180
github.com_AdRoll_goamz_s3.query.pN29_github.com_AdRoll_goamz_s3.S3
	/home/ubuntu/go/src/github.com/AdRoll/goamz/s3/s3.go:931
github.com_AdRoll_goamz_s3.PutReader.pN33_github.com_AdRoll_goamz_s3.Bucket
	/home/ubuntu/go/src/github.com/AdRoll/goamz/s3/s3.go:374
github.com_AdRoll_goamz_s3.Put.pN33_github.com_AdRoll_goamz_s3.Bucket
	/home/ubuntu/go/src/github.com/AdRoll/goamz/s3/s3.go:334
craft.putMarkerOnS3
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/marker.go:156
craft.downloadMarker
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/marker.go:89
created by github.com_testar_test_mount_of_doom_craft.HandleNewMarkers
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/marker.go:147

goroutine 2040 [select]:

goroutine 2039 [IO wait]:

goroutine 419 [select]:
craft.getDataFromDatas
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:102
github.com_testar_test_mount_of_doom_craft.GetTestData
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft/craft_test_data.go:141
main.craftTestID
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/craft_test.go:232
main.handleCraftTestMessage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:95
main.$nested0
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:122
created by main.handlePackage
	/home/ubuntu/go/src/github.com/testar-test/mount-of-doom/main.go:121
```

**Comment by julienfouilhe** [comment]
A quick update: I tried to roll back to `v1.0.1`, it doesn't help. It may not be your fault.

**Comment by mreiferson** [comment]
try with different (older) versions of Go?

**Comment by mreiferson** [comment]
(gonna close, please re-open if you think there's something on the `go-nsq` side)
